# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bac476d19d28cbe2bfd1acf03079b86e6ae75be1ad5f278686989a74a06b78c95b9d639c4f3146e2f7337b73ed1140fdb264fe65ca6d50145400c8319ede8dc

test:
  secret_key_base: abc4d13014d466f83105530cb2b7ae6420d60e1df3d62c68142ad4468576670cf7a3c60fe6bceb4414293e76511fd52ecce41bebc4037b0016ecbd42af0db4b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
